const coursesData = {
  foundations: [
    "What is The Odin Project?",
    "Should you skip anything in The Odin Project or complete it non-linearly?",
    "What kind of web developer will The Odin Project teach you to be?",
    "What are the different types of careers you could have?",
    "What are some of the tools you’ll be using regularly?",
    "What are the two modes your mind switches between during the learning process, and how do they differ?",
    "When you’re stuck on a programming problem, what three main strategies does the curriculum recommend trying?",
    "Why does the curriculum recommend against setting strict deadlines for completing The Odin Project?",
    "What is the “XY Problem”?",
    "What 5 things should your questions include?",
    "How do you join The Odin Project’s Discord server?",
    "What makes a good question that’s easier for others to help with?",
    "How can you more effectively help others with their coding problems?",
    "What is a web server?",
    "What is a network?",
    "What is the internet?",
    "What is an IP address?",
    "What is a router?",
    "What is an ISP?",
    "What are packets and how are they used to transfer data?",
    "What is a client?",
    "What is a server?",
    "What is a web page?",
    "What is a web browser?",
    "What is a search engine?",
    "What is a DNS request?",
    "Which browser are you currently using?",
    "In your own words, describe the process that takes place when you initiate a search on google.com in terms of what we discussed.",
    "What operating systems does The Odin Project support?",
    "What browser does The Odin Project support?",
    "What is a code editor?",
    "Which code editor does The Odin Project support?",
    "What is the command line?",
    "How do you open the command line on your computer?",
    "How can you navigate to a particular directory?",
    "Where will <code>cd</code> on its own navigate you to?",
    "Where will <code>cd ..</code> navigate you to?",
    "How do you display the name of the directory you are currently in?",
    "How do you display the contents of the directory you are currently in?",
    "How do you create a new directory?",
    "How do you create a new file?",
    "How do you destroy a directory or file?",
    "How do you rename a directory or file?",
    "What is Git?",
    "What is GitHub?",
    "What authentication method are we setting up with Git: SSH or HTTPS?",
    "What kind of program is Git?",
    "What are the differences between Git and a text editor in terms of what they save and their record keeping?",
    "Does Git work at a local or remote level?",
    "Does GitHub work at a local or remote level?",
    "Why is Git useful for developers?",
    "Why are Git and GitHub useful for a team of developers?",
    "How do you create a new repository on GitHub?",
    "How do you copy a repository onto your local machine from GitHub?",
    "What is the default name of your remote connection?",
    "Explain what <code>origin</code> is in <code>git push origin main</code>.",
    "Explain what <code>main</code> is in <code>git push origin main</code>.",
    "Explain the two-stage system that Git uses to save files.",
    "How do you check the status of your current repository?",
    "How do you add files to the staging area in Git?",
    "How do you commit the files in the staging area and add a descriptive message?",
    "How do you push your changes to your repository on GitHub?",
    "How do you look at the history of your previous commits?",
    "What do HTML and CSS stand for?",
    "Between HTML and CSS, which would you use for putting paragraphs of text on a webpage?",
    "Between HTML and CSS, which would you use for changing the font and background color of a button?",
    "What is the difference between HTML, CSS and JavaScript?",
    "What is an HTML tag?",
    "What are the three parts of an HTML element?",
    "What are void elements, and how are they different from regular HTML elements?",
    "What is the purpose of the doctype declaration?",
    "What is the HTML element?",
    "What is the purpose of the head element?",
    "What is the purpose of the body element?",
    "How do you create a paragraph in HTML?",
    "How do you create a heading in HTML?",
    "How many different levels of headings are there and what is the difference between them?",
    "What element should you use to semantically mark text as important?",
    "What element should you use to semantically emphasize text?",
    "What relationship does an element have with any nested elements within it?",
    "What relationship do two elements have if they are at the same level of nesting?",
    "How do you create HTML comments?",
    "What HTML element is used to create an unordered list?",
    "What HTML element is used to create an ordered list?",
    "What HTML element is used to create list items within both unordered and ordered lists?",
    "What element is used to create a link?",
    "What is an attribute?",
    "What attribute tells links where to go to?",
    "What security considerations must be taken if you wish to use the target attribute to open links in a new tab/window?",
    "What is the difference between an absolute and relative link?",
    "Which element is used to display an image?",
    "What two attributes do images always need to have?",
    "How do you access a parent directory in a filepath?",
    "What are the four main image formats that you can use for images on the web?",
    "What are two benefits of having well-written commit messages and a good commit history?",
    "How many characters should the subject line of your commit message be?",
    "What is the syntax for class and ID selectors?",
    "How would you apply a single rule to two different selectors?",
    "Given an element that has an id of <code>title</code> and a class of <code>primary</code>, how would you use both attributes for a single rule?",
    "What does the descendant combinator do?",
    "What are the names of the three ways to add CSS to HTML?",
    "What are the main differences between the three ways of adding CSS to HTML?",
    "Between a rule that uses one class selector and a rule that uses three type selectors, which rule has the higher specificity?",
    "How do you select a specific element on your page with your browser’s developer tools?",
    "What does a strikethrough in a CSS declaration mean in your browser’s developer tools?",
    "How do you change CSS in real time on specific elements of a web page with your browser’s developer tools?",
    "From inside to outside, what is the order of box-model properties?",
    "What does the <code>box-sizing</code> CSS property do?",
    "What is the difference between the standard and alternative box model?",
    "Would you use <code>margin</code> or <code>padding</code> to create more space between 2 elements?",
    "Would you use <code>margin</code> or <code>padding</code> to create more space between the contents of an element and its border?",
    "Would you use <code>margin</code> or <code>padding</code> if you wanted two elements to overlap each other?",
    "How do you set the alternative box model for all of your elements?",
    "How do you center an element horizontally?",
    "What is the difference between a block element and an inline element?",
    "What is the difference between an inline element and an inline-block element?",
    "Is an <code>h1</code> block or inline?",
    "Is <code>button</code> block or inline?",
    "Is <code>div</code> block or inline?",
    "Is <code>span</code> block or inline?",
    "What’s the difference between a flex container and a flex item?",
    "How do you create a flex item?",
    "What are the 3 values defined in the shorthand <code>flex</code> property (e.g. <code>flex: 1 1 auto</code>)?",
    "What are the 3 defined values for the flex shorthand <code>flex:auto</code>?",
    "How do you make flex items arrange themselves vertically instead of horizontally?",
    "In a <code>column</code> flex-container, what does <code>flex-basis</code> refer to?",
    "In a <code>row</code> flex-container, what does <code>flex-basis</code> refer to?",
    "Why do the previous two questions have different answers?",
    "What is the difference between <code>justify-content</code> and <code>align-items</code>?",
    "How do you use flexbox to completely center a div inside a flex container?",
    "What’s the difference between <code>justify-content: space-between</code> and <code>justify-content: space-around</code>?",
    "What three keywords can you use to declare new variables?",
    "Which of the three variable declarations should you avoid and why?",
    "What rules should you follow when naming variables?",
    "What happens when you add numbers and strings together?",
    "How does the Modulo (%), or Remainder, operator work?",
    "How do you increment and decrement a number?",
    "What’s the difference between prefixing and postfixing increment/decrement operators?",
    "What is operator precedence and how is it handled in JS?",
    "How do you access developer tools and the console?",
    "How do you log information to the console?",
    "What does unary plus operator do to string representations of integers? eg. +”10”",
    "What is Node.js?",
    "Should we install the absolute latest version of Node or the latest LTS version?",
    "What are the eight data types in JavaScript?",
    "Which data type is NOT primitive?",
    "What is the relationship between null and undefined?",
    "What is the difference between single, double, and backtick quotes for strings?",
    "What is the term for joining strings together?",
    "Which type of quote lets you embed variables/expressions in a string?",
    "How do you embed variables/expressions in a string?",
    "How do you use escape characters in a string?",
    "What is the difference between the slice/substring string methods?",
    "What are the three logical operators, and what do they stand for?",
    "What are the comparison operators?",
    "What are truthy and falsy values?",
    "What are the falsy values in JavaScript?",
    "What is the syntax for an if/else conditional?",
    "What is the syntax for a switch statement?",
    "What is the syntax for a ternary operator?",
    "What is nesting?",
    "How do you open developer tools?",
    "How do you change screen size of a website using developer tools?",
    "What is a breakpoint?",
    "How do you set a breakpoint?",
    "What are functions useful for?",
    "How do you invoke a function?",
    "What are anonymous functions?",
    "What is function scope?",
    "What are return values?",
    "What are arrow functions?",
    "What is the difference between a function declaration and a function expression?",
    "What are the three stages in the problem solving process?",
    "Why is it important to clearly understand the problem first?",
    "What can you do to help get a clearer understanding of the problem?",
    "What are some of the things you should do in the planning stage of the problem solving process?",
    "What is an algorithm?",
    "What is pseudocode?",
    "What are the advantages of breaking a problem down and solving the smaller problems?",
    "What are three reasons why you may see a TypeError?",
    "What is the key difference between an error and a warning?",
    "What is one method you can use to resolve an error?",
    "Why is it important to write clean code?",
    "What are some good principles for keeping code clean?",
    "What is the difference between good comments and bad comments?",
    "What are loops useful for?",
    "What is the break statement?",
    "What is the continue statement?",
    "What is an array?",
    "What are arrays useful for?",
    "How do you access or change an array element?",
    "What are some useful array methods?",
    "What is the advantage of writing automated tests?",
    "What is the DOM?",
    "How do you target the nodes you want to work with?",
    "How do you create an element in the DOM?",
    "How do you add an element to the DOM?",
    "How do you remove an element from the DOM?",
    "How can you alter an element in the DOM?",
    "When adding text to a DOM element, should you use textContent or innerHTML? Why?",
    "Where should you include your JavaScript tag in your HTML file when working with DOM nodes?",
    "How do “events” and “listeners” work?",
    "What are three ways to use events in your code?",
    "Why are event listeners the preferred way to handle events?",
    "What are the benefits of using named functions in your listeners?",
    "How do you attach listeners to groups of nodes?",
    "What is the difference between the return values of <code>querySelector</code> and <code>querySelectorAll</code>?",
    "What does a “NodeList” contain?",
    "What is the difference between the “capturing phase” and “bubbling phase”?",
    "What are branches in git?",
    "How do you create a new branch?",
    "How do you merge a branch back into main?",
    "What is one use case for branches?",
    "What is the difference between objects and arrays?",
    "How do you access object properties?",
    "How do primitives and object types differ when you assign them to other variables, or pass them into functions?",
  ],
  intermediateHtmlAndCss: [
    "What is the purpose of the Intermediate HTML and CSS Course?",
    "What is the <code>xmlns</code> attribute?",
    "What are some situations where you <em>wouldn’t</em> want to use SVG?",
    "What are the benefits of “inlining” your SVGs? What are the drawbacks?",
    "What is a table?",
    "Why is it a bad idea to use HTML Tables for page layout?",
    "What are caption elements useful for?",
    "What is the scope attribute?",
    "Why would you want to use a CSS reset?",
    "Are resets required?",
    "Why would you want to use <code>em</code> or <code>rem</code> for font-size instead of <code>px</code>?",
    "What are some instances where you might want to use <code>vh</code> and <code>vw</code>?",
    "What are some instances where you might want to use <code>px</code> instead of a relative unit?",
    "What are the 2 ways to add fonts that are not installed on a user’s computer?",
    "What is the ‘system font stack’ and why would you want to use it?",
    "Which property would you use to increase or decrease the space between letters in a word?",
    "Which property would you use to increase or decrease the space between lines in a paragraph?",
    "Which property would you use to make an element transparent?",
    "Which property would you use to make a background image tile?",
    "Which property would you use to add scrollbars to an element?",
    "Which property would you use to add a shadow behind an element?",
    "Which property would you use to create rounded corners on an element?",
    "How would you use border-radius to make a circular element?",
    "What is the difference between the child combinator and the descendant combinator?",
    "How does the syntax of pseudo-classes and pseudo-elements differ?",
    "Do pseudo-classes exist somewhere in HTML? Do pseudo-elements?",
    "Name two ways you could select every second child of an element, starting with the first.",
    "What is the difference between <code>div:first-child</code> and <code>div:last-child</code>? What will each select?",
    "What selector would you use to style a button a user is currently hovering over? How about one that is currently being clicked on?",
    "How could you select all input elements with a type of text?",
    "How could you select all classes that begin with <code>thunder</code>?",
    "What is the difference between static and relative positioning?",
    "What is absolute positioning useful for?",
    "What is the difference between fixed and sticky positioning?",
    "What are the four CSS math functions we covered above?",
    "How do we use CSS math functions in our CSS?",
    "How can CSS functions help make websites and applications more responsive?",
    "How would you declare a custom property with a name of <code>text-color</code>?",
    "How would you access a custom property with a name of <code>background-color</code>?",
    "Where would you declare a custom property to have its scope be global and accessible by all other selectors?",
    "Where would you declare a custom property so that a user’s theme setting from their OS or browser was taken into account?",
    "What is the most used browser currently?",
    "What was the original name of the first web browser?",
    "How are mobile browsers different on Apple mobile operating systems from Android?",
    "What are CSS frameworks?",
    "What are CSS preprocessors?",
    "Explain what the form element is for and what two attributes it should always include.",
    "Explain what form controls are at a high level.",
    "What is the <code>name</code> attribute for?",
    "What are the three most common form controls you can use for allowing users to select predefined options?",
    "What are the three types of buttons in HTML?",
    "What are the two most challenging aspects of styling forms?",
    "What does the <code>required</code> validation do?",
    "What validations can you use for checking text length?",
    "How can you validate the minimum and maximum of numeric inputs?",
    "What can you use the pattern validation for?",
    "What pseudo CSS selectors are available for styling valid and invalid inputs?",
    "How can you use Flex to make a two-dimensional layout?",
    "Why was CSS Grid introduced?",
    "Which CSS layout module would you use to easily make equal sized items in a container?",
    "How does an HTML element become a grid item?",
    "What is the space between lines on the grid?",
    "How do you set gutters (also known as alleys) in the grid?",
    "Describe what happens when you have more content than defined tracks.",
    "How could you change the size for those undefined tracks?",
    "Explain the difference between a track and a line.",
    "What is the smallest unit on a grid?",
    "What kind of value do we give to the <code>grid-column-start</code> or <code>grid-column-end</code> properties?",
    "Which property can we use to combine all the start and end values for a grid item?",
    "Which grid container property can map out a visual structure of grid items?",
    "How do you create several grid tracks of the same size without manually typing each one out?",
    "What is the difference between a static and dynamic size value?",
    "How can you assign a grid track a flexible value that changes depending on the remaining space available in the grid?",
    "How can you assign grid tracks an uneven distribution of the remaining space in a grid?",
    "Which CSS functions will return the <em>smallest</em> or <em>largest</em> value supplied to them?",
    "Which CSS Grid-only function allows you to supply a minimum and maximum track size that is calculated in realtime?",
    "Which global CSS function allows you to supply a minimum, ideal, and maximum value that is calculated in realtime?",
    "What attribute of <code>repeat()</code> can be used to fill in as many grid tracks as possible, given certain constraints?",
    "What is the difference between <code>auto-fit</code> and <code>auto-fill</code>?",
    "When might you use Flexbox over Grid?",
    "When might you use Grid over Flexbox?",
    "When might you use the two of these tools together?",
  ],
  javascript: [
    "What are two ways you can use objects to organize code?",
    "What is a method?",
    "In object methods, what is the <code>this</code> keyword used for?",
    "How do you write an object constructor and instantiate the object?",
    "How can you prevent that an object constructor is called without using the keyword <code>new</code>?",
    "What is a prototype and how can it be used?",
    "What is prototypal inheritance?",
    "What are the basic do’s and don’t’s of prototypal inheritance?",
    "How does <code>this</code> behave in different situations?",
    "How does scope work in JavaScript?",
    "What are closures?",
    "What common issues can you face when working with constructors?",
    "What are private variables in factory functions and how can they be useful?",
    "How can we compose with factory functions?",
    "How does the module pattern work?",
    "What does IIFE stand for and what are they?",
    "How do factory functions help with encapsulation?",
    "What differences are there between object constructors and classes?",
    "What are getters and setters?",
    "How is inheritance used with classes?",
    "What are some private class features?",
    "What are static properties?",
    "Before ES6 modules, how would you privatize a variable from being accessible in other files?",
    "Before ES6 modules, how would you expose variables to be accessible in later files?",
    "What are some benefits of writing code in modules?",
    "What is the difference between default and named exports?",
    "What is an entry point?",
    "How do you link a module script in HTML?",
    "What is npm?",
    "What file does npm use that contains all information about dependencies?",
    "What is a bundler?",
    "What is Webpack?",
    "How do you bundle JavaScript?",
    "How do you load CSS using Webpack?",
    "How do you automatically build HTML files in <code>dist</code> using Webpack?",
    "How would you handle assets like local image files?",
    "What Webpack tool could you use during development to view changes to your website live?",
    "How does using a source map help with development?",
    "Where do npm scripts live?",
    "How do you define and run npm scripts?",
    "What are the two Webpack modes?",
    "What tool allows you to split your Webpack configuration file with minimal duplication?",
    "What is a template repository, and how would you create one?",
    "What is JSON?",
    "How do you convert a JSON string into a JavaScript object?",
    "How do you convert a JavaScript object into a JSON string?",
    "What is the “Single Responsibility Principle”?",
    "What are the additional SOLID principles?",
    "What are “tightly coupled” objects and why do we want to avoid them?",
    "Why is favoring composition over inheritance suggested?",
    "What is linting?",
    "Which problems can linting prevent?",
    "What are some of the benefits of using a formatter?",
    "What is Prettier?",
    "Why should you install linters and/or formatters as dev dependencies in your project?",
    "What is the importance of validating HTML forms before submitting them to a server?",
    "What are the two types of client-side form validation?",
    "How does JavaScript Constraint Validation API provide more control and customization of form validation?",
    "What is ES6?",
    "Since ES6, what release schedule has been used for new ECMAScript versions?",
    "Why might someone need to be careful about using brand new JavaScript features?",
    "What tool can be used to transpile newer JavaScript for older browser support?",
    "What is a callback?",
    "What is a promise?",
    "When should you use promises over callbacks?",
    "What does the <code>.then()</code> function do?",
    "What is an API?",
    "How is access to an API restricted?",
    "How do you fetch and extract data from an API?",
    "What does the <code>async</code> keyword do?",
    "What does the <code>await</code> keyword do?",
    "What is returned from an <code>async</code> function?",
    "What happens when an error is thrown inside an <code>async</code> function?",
    "How can you handle errors inside an <code>async</code> function?",
    "What are the benefits of TDD?",
    "What are some common jest matchers?",
    "What is tightly coupled code?",
    "What are the two requirements for a function to be pure?",
    "What are side effects and why is it important to identify them when testing a function?",
    "What should you try before testing tightly coupled code?",
    "How can you test code that can’t be decoupled?",
    "What is mocking?",
    "When would you use a mock function?",
    "How should you test incoming query messages?",
    "Why should you not test implementation?",
    "Should you test private methods?",
    "Why should you not test outgoing messages with no side effects?",
    "What is an Algorithm?",
    "What is the importance of algorithms in web development?",
    "What is pseudocode?",
    "How would you briefly define a recursive function?",
    "What is the point of recursion? Is it more efficient than using a plain loop?",
    "What are the 2 essential parts in a recursive function?",
    "Why is “stack overflow” relevant to a recursive problem?",
    "What is Big O?",
    "What are the most common Big O Notations?",
    "Why use Big O?",
    "What is Big Omega and why isn’t it as useful?",
    "Why don’t constants make a difference in Big O?",
    "What is space complexity?",
    "How do we measure space complexity?",
    "What is a situation where auxiliary space analysis is useful?",
    "What is the difference between a stack and a queue?",
    "What are the enqueue and dequeue properties?",
    "What is a linked list? What is a node?",
    "Which recursive problem-solving method/algorithm design principle does binary search implement?",
    "What data structure would you use to defer/store nodes in a breadth-first tree traversal?",
    "What data structure would you use to defer/store nodes in a depth-first tree traversal?",
    "What does it mean to hash?",
    "What are buckets?",
    "What is a collision?",
    "When is it a good time to grow our buckets array?",
    "How can you amend your last commit?",
    "What does it mean for branches to be pointers?",
    "What is the difference between <code>git reset</code>, <code>git reset --soft</code>, and <code>git reset --hard</code>?",
    "How would you squash two commits into one?",
    "How would you split a commit into two smaller commits?",
    "What is a safe way to forcefully push history changes to a remote repository?",
    "What are the dangers of history-changing operations?",
    "What are best practices of history-changing operations?",
    "What name is typically given for a Git remote that points to a repo that’s been forked?",
    "Can you directly send your changes to a repository that you don’t own/have write access to?",
    "What should you do immediately before merging main into your feature branch?",
  ],
  advancedHtmlAndCss: [
    "What are the four main functions of the <code>transform</code> property?",
    "Which function can be used to move an object through space on the X, Y, or Z axis?",
    "Which function can be used to make an object larger or smaller on the X, Y, or Z axis?",
    "What additional function is required for 3D transforms?",
    "Are all CSS properties animatable?",
    "What are the long and short-hand notations for transitions?",
    "What is the stacking context?",
    "Why do you need to keep an eye on repaints?",
    "What are the long and short-hand notations for CSS animations?",
    "How do you add keyframes to an animation?",
    "When would you use an animation over a transition (and vice versa)?",
    "What is web accessibility?",
    "Who truly benefits from accessibility features?",
    "What is the purpose of the Web Content Accessibility Guidelines?",
    "What are the 4 principles of the WCAG?",
    "Why is semantic HTML important for accessibility?",
    "What are the seven HTML elements that define landmarks on a page?",
    "What is a contrast ratio?",
    "What are two ways you can check a contrast ratio using your dev tools?",
    "What should you avoid when conveying information to users?",
    "What are two things that interactive elements must have for keyboard users?",
    "What are focus styles?",
    "Why should you never completely remove focus styles from an element?",
    "What is the tab order?",
    "What is the best way to hide hidden content from assistive technologies?",
    "What are three rules you should follow in order to provide meaningful links?",
    "What information should you inform users of in order to provide meaningful error messages in forms?",
    "When should you use the empty string/null value for the <code>alt</code> attribute?",
    "What purpose does WAI-ARIA serve?",
    "What are the four things ARIA can’t do?",
    "What are the five rules of ARIA?",
    "What is the accessibility tree?",
    "What are the differences between the three ARIA labels?",
    "What does the <code>aria-hidden</code> attribute do?",
    "What are some of the various accessibility features available in your browser’s DevTools?",
    "Which third-party accessibility auditing tool is available in the Chrome DevTools by default?",
    "What is Responsive Design?",
    "What is natural responsiveness?",
    "When should you avoid using fixed widths?",
    "When should you avoid using fixed heights?",
    "In what situations might it be appropriate to use a fixed height or width?",
    "When might percentages interfere with responsiveness?",
    "What is the main difference between <code>object-fit</code> and <code>background-size</code>?",
    "How can you define a width and a height on an <code>img</code> without distorting it?",
    "Why would you want to provide different images at different screen resolutions?",
    "When would you want to use an <code>img</code> with a <code>srcset</code> vs a <code>picture</code>?",
    "How do you define a media query to create a mobile layout for your site?",
    "What is the difference between <code>max-width</code> and <code>min-width</code> in a media query definition?",
    "What is the difference between a media query and a container query?",
  ],
  react: [
    "What is the purpose of React?",
    "What are the benefits of using React?",
    "What are some of the ways we can start a new React project?",
    "Why should we initially be using pre-made toolchains instead of making our own?",
    "What is Vite and why would we use it?",
    "What command can we run to scaffold a new React project using Vite?",
    "What is in the <code>public</code> folder?",
    "What is in the <code>src</code> folder?",
    "Why are the React Developer Tools useful?",
    "What does a React component look like?",
    "How would you create a functional component?",
    "How do you export and then import a component?",
    "What is JSX?",
    "Why do we use JSX?",
    "What are the three rules of JSX?",
    "How do you reference a dynamic value inside of your JSX?",
    "How does data flow between React components? From child to parent? From parent to child? Both?",
    "Why do we use props in React?",
    "How do we define default properties on a React component? What are some benefits in doing so?",
    "How can we pass functions as props?",
    "How do you render a list of elements/components in JSX?",
    "What are the ways you could render UI conditionally?",
    "How would you conditionally return JSX?",
    "Why does React need keys?",
    "Why does React need keys when rendering lists?",
    "How do you use keys?",
    "Where should the key value ideally come from?",
    "When can we use an array index as the key value?",
    "What is an anti-pattern when using keys?",
    "How are keys related to state?",
    "What is state?",
    "What is the <code>useState</code> hook and how would you use it?",
    "What happens to a component when one of its states is changed?",
    "What are some of the rules of hooks?",
    "What should you keep in mind while declaring state?",
    "Why should we always use <code>setState</code> to update our state?",
    "What does “state as a snapshot” mean?",
    "What’s the difference between passing a value vs a callback to the <code>setState</code> function?",
    "Why should we always provide a new Object to <code>setState</code>?",
    "Why would you want to control a component?",
    "What is an effect?",
    "What constitutes a <code>useEffect</code> hook?",
    "What is the one question we can ask to know when to use an effect?",
    "What do we mean by lifting up the state?",
    "How do props get used in a class-based component?",
    "How does JSX get displayed?",
    "How do we deal with state in a class-based component?",
    "How do you restore the context of <code>this</code> in a method?",
    "What is the only required lifecycle method?",
    "What lifecycle method should you use for initial data fetching?",
    "When you want to act upon change of the DOM, or of state, what lifecycle method would you use?",
    "When performing cleanup actions, what lifecycle method should be used?",
    "How does the useEffect hook combine some of the lifecycle methods?",
    "Why might you want to test your UI?",
    "What packages are required for React testing?",
    "What is the significance of the user-event package?",
    "What does the <code>render</code> method do?",
    "What is the most preferred method for querying?",
    "How would you test for a click event with <code>userEvent</code>?",
    "What is the advantage of snapshot tests?",
    "What are the disadvantages of snapshot tests?",
    "How can you mock a callback handler?",
    "How can you mock a child component?",
    "What does client-side routing mean?",
    "How do you set up a basic router?",
    "What should be used in place of “a” tags to enable client-side routing?",
    "How do you create nested routes?",
    "What do you mean by dynamic segments or URL params?",
    "How do you handle errors from bad URLs?",
    "How do you pass data from parent to child through an <code>&lt;Outlet /&gt;</code> component?",
    "How do you create protected routes?",
    "How do you test components that use React Router?",
    "How can you fetch data from an API in React?",
    "Why should you manually throw errors in fetch requests?",
    "How can you avoid waterfalling requests?",
    "How can you use CSS Modules in your React app?",
    "What does CSS-in-JS mean?",
    "What are component libraries?",
    "What problems can prop drilling cause?",
    "How can we avoid problems with prop drilling?",
    "What are the benefits of using the Context API over passing props down through multiple levels of components?",
    "What are the drawbacks in using the Context API?",
    "What are reducers?",
    "How would you declare a reducer?",
    "What does the dispatch function do?",
    "What steps can you follow to migrate from useState to useReducer?",
    "Why should you prefer useRef hook over other DOM manipulation methods like querySelector?",
    "What is the difference between useMemo and useCallback?",
    "How do useMemo and useCallback help optimize the performance of React components?",
    "When should you memoize a value?",
    "What is React Compiler and how does it optimize React applications?",
    "What are some of the topics you can explore next?",
    "How to prevent your app “forgetting” changes made on a page reload?",
  ],
  databases: [
    "What is a database?",
    "What are relational databases?",
    "What is a Primary Key?",
    "What is SQL?",
    "How do you get all the records from a table in SQL?",
    "How do you insert a record in SQL?",
    "What is the difference between a foreign key and a primary key?",
    "Where is the setup information for your database stored?",
    "What are the important parts of a SQL command?",
    "Which SQL statement is associated with “Read” from the CRUD acronym?",
    "Which <code>JOIN</code> statement keeps only the rows from both tables where they match up?",
    "How do you use an aggregate function?",
    "In which situation would you use the <code>HAVING</code> clause?",
    "Why can’t I just use code to process my database data?",
  ],
  nodejs: [
    "What is back-end development?",
    "How many parts does the back end consist of?",
    "What do we name each part of the back end?",
    "Where does the back end store its data?",
    "What is Node?",
    "What is a File System Module? How and why would you use it?",
    "What can you use to debug Node?",
    "What are environment variables?",
    "What might you want to use environment variables for?",
    "How can you load environment variables from a <code>.env</code> file?",
    "How do you access environment variables in a Node app?",
    "What data type will an environment variable always be?",
    "Should you push your <code>.env</code> file to GitHub?",
    "What problems do frameworks solve?",
    "What are some popular front-end and back-end frameworks?",
    "How can you describe the process of choosing a framework?",
    "What is Express?",
    "What happens when a server receives a request?",
    "What can we use to tell Express to send a file in response to a request?",
    "What can you use to automatically restart your server when you make changes to a file?",
    "How can you define a route that will only match a specific HTTP verb?",
    "How can you define a route that will match all HTTP verbs?",
    "How can you define path patterns for your routes to match?",
    "How does the order of your routes affect which routes get matched?",
    "What object gets populated with route parameters?",
    "How do you access query parameters within routes?",
    "How do you extract routes to an individual router?",
    "We have a router for paths starting with <code>/users</code>. Inside that router, what path should a GET route have to match a GET request to the <code>/users/delete</code> path?",
    "What are the common response methods and their use cases?",
    "What are the types of middleware?",
    "How does a middleware get executed? In which order?",
    "What does calling the next function do? What if we pass an error argument?",
    "What are the other arguments you can pass to the next function?",
    "What is a controller?",
    "What is the difference between a controller and a middleware?",
    "What happens if you define a middleware function with four parameters?",
    "What would you do to create a custom error?",
    "What are template engines for that differs from rendering an SPA on the client?",
    "How do you configure EJS for Express projects?",
    "What is the difference between “&lt;%” and “&lt;%=” tags?",
    "How do you render a view in a controller callback?",
    "How can templates be included in other templates?",
    "What’s the difference between static and dynamic websites?",
    "What does ‘PaaS’ stand for?",
    "What are the advantages of using a PaaS hosting provider?",
    "What is an instance?",
    "What steps can you take to diagnose an issue that arises during deployment?",
    "What steps can you take to diagnose an issue that only appears after deployment?",
    "What are the attributes of a form element and what do they do?",
    "How do you install and import express-validator in your project?",
    "How do you validate and sanitize form input using express-validator?",
    "What is the difference between validation and sanitization?",
    "How do you handle validation errors in Express routes?",
    "What is the importance of escaping HTML characters in a form?",
    "Why is data persistence important in web applications?",
    "What is the PostgreSQL shell?",
    "How do you create a db and table via PostgreSQL shell?",
    "What is node-postgres and how do you use it?",
    "When should you use a client or a pool in pg?",
    "How would you integrate db query functions in your Express app?",
    "How would you populate the db via a script?",
    "Which passport.js strategy did we use in the lesson?",
    "Why does passport.js create a cookie?",
    "What does the <code>bcrypt.compare()</code> function do?",
    "Why should we include bcrypt when we begin a project?",
    "What are some of the challenges of using raw sql?",
    "What is Prisma schema and how is it useful?",
    "What is the Prisma client?",
    "How does Prisma client know about the models in your schema?",
    "What is Prisma migrate?",
    "How do you define a relation in Prisma schema?",
    "How can you get all records from a table using Prisma client?",
    "What does REST stand for?",
    "What are HTTP verbs and why are they important to an API?",
    "What is the Same-Origin Policy?",
    "How do you enable CORS in your Express app?",
    "Which HTTP verb does each letter in CRUD (Create, Read, Update, Delete) correspond to?",
    "What is a JSON web token?",
    "What are two things a secure token will do?",
    "Where in the code is a secure token passed?",
    "What is the motivation behind SuperTest?",
    "What is the purpose of <code>done</code>? What convenience does SuperTest provide concerning it?",
    "What is the difference in handling errors when using .end() method in conjunction with .expect() provided by SuperTest?",
    "What are the methods provided by SuperAgent to handle multipart requests and how to use them?",
    "When should you unit test database operations?",
    "How do you set up and use a test database for integration testing?",
    "What is a great first step after finishing the curriculum?",
    "How can you get involved with contributing to The Odin Project curriculum?",
  ],
  gettingHired: [
    "What is a professional network?",
    "Why is a professional network useful?",
    "How can you build a professional network?",
    "How can you maintain your professional network?",
    "What are the main steps in the overall strategy for getting hired?",
    "Why is it important to assess your current situation before starting a job search?",
    "What questions can help you define your career goals and priorities?",
    "What questions can help you identify your strengths and weaknesses as a job candidate?",
    "What are the 3 main things hiring managers look for?",
    "What are the advantages to getting an internship?",
    "Why is it important to build a portfolio of work as you prepare for your job search?",
    "What steps can you take to improve your web presence before potential employers search for you online?",
    "How can you organize your job search effectively?",
    "What are high-probability sources for finding job openings?",
    "What strategies can you use to avoid wasting time on unworthy job leads?",
    "What are some strategies to get noticed by companies you want to work for?",
    "How can you maintain perseverance during the job search?",
    "How can you tailor your resume for different positions?",
    "What is the purpose of a phone screen?",
    "What strategies can you use to succeed in a technical interview?",
    "How should you approach a take-home technical challenge?",
    "How to approach compensation discussions?",
    "How should you handle an offer?",
  ],
};
export default coursesData;
